export class LoginResponseModel {
  constructor(
    public access_token: string = '',
    public expires_in: string = '',
    public status: string = '',
    public incidentId: string = '',
    public message: string = '',
    public messageType: string = '',
    public messageTitle: string = '',
    public showCloseButton: boolean = false,
    public closeHtml: string = '',
    public requiresStudent: boolean = false,
    public requiresRelationship: boolean = false,
    public firstName: string = '',
    public lastName: string = '',
    public cartItemCount: number = 0,
    public districtKey: string = '',
    public districtName: string = '',
    public isNewExperience: boolean = false,
    public allPaymentsSuspended: boolean = true,
    public allPaymentsResumeDate: string = '',
    public mealPaymentsSuspended: boolean = true,
    public mealPaymentsResumeDate: string = '',
    public isBlockACH: boolean = false,
    public isBlockPayments: boolean = false,
    public state: string = '',
    public isAchAllowed: boolean = false,
    public isAutoPayEnabled: boolean = false,
    public isAlertsAllowedDistrict: boolean = false,
    public isDisableMealPaymentsDistrict: boolean = false,
    public isFroEnabled: boolean = false,
    public externalNavRequest: string = '',
    public isOldExperienceAllowed: boolean = true,
    //public availableDistricts: any,
  ) { }
}
